# Generated by Django 5.1 on 2024-09-19 12:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0004_rename_date_of_birth_profiledb_dateofbirth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('😊', 'Happy'), ('😔', 'Sad'), ('😐', 'Neutral')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_images/')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date_created')},
            },
        ),
    ]
