# Generated by Django 5.1 on 2024-09-19 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0005_journalentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(choices=[('😊', 'Happy'), ('😔', 'Sad'), ('😡', 'Angry'), ('😎', 'Excited'), ('😌', 'Calm')], max_length=10),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.registerdb'),
        ),
    ]
