# Generated by Django 5.1 on 2024-09-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0008_alter_question_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
