# Generated by Django 5.1 on 2024-09-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0010_event_organizer_info'),
        ('HealthApp', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DoctorApp.doctorregisterdb'),
        ),
    ]
