# Generated by Django 5.1 on 2024-10-03 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0011_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
