# Generated by Django 5.1 on 2024-10-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0012_response_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='created_at',
        ),
        migrations.AddField(
            model_name='response',
            name='stress_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
