# Generated by Django 5.1 on 2024-10-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0014_response_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='stress_level',
            field=models.IntegerField(default=0),
        ),
    ]
