# Generated by Django 5.1 on 2024-10-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0015_alter_response_stress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='stress_level',
            field=models.CharField(max_length=20),
        ),
    ]
