# Generated by Django 5.1 on 2024-10-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0016_alter_response_stress_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='stress_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20, null=True),
        ),
    ]
