# Generated by Django 5.1 on 2024-10-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0017_alter_response_stress_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HealthApp.registerdb'),
            preserve_default=False,
        ),
    ]
