# Generated by Django 5.1 on 2024-10-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0018_response_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='stress_level',
            field=models.IntegerField(null=True),
        ),
    ]
