# Generated by Django 5.1 on 2024-10-04 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0019_alter_response_stress_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='screening_id',
            field=models.IntegerField(null=True, blank=True),  # Allow nulls
        ),
    ]
