# Generated by Django 5.1 on 2024-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0021_alter_response_screening_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='screening_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
