# Generated by Django 5.1 on 2024-10-04 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0023_alter_response_screening_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='screening_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='stress_level',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
