# Generated by Django 5.1 on 2024-10-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0027_communitypost_votes_alter_communitypost_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.registerdb')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
