# Generated by Django 5.1 on 2024-10-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0029_remove_reply_comment_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
