# Generated by Django 5.1 on 2024-10-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_recipe'),
        ('HealthApp', '0031_exerciselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_text', models.TextField()),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.gratitudeprompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.registerdb')),
            ],
        ),
    ]
