# Generated by Django 5.1 on 2024-10-14 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_recipe'),
        ('HealthApp', '0032_gratitudeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.registerdb')),
            ],
        ),
    ]
