# Generated by Django 5.1 on 2024-10-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0034_gratitudeentry_challenge_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeprogress',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
