# Generated by Django 5.1 on 2024-10-24 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0035_challengeprogress_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthApp.registerdb'),
        ),
    ]
