# Generated by Django 5.1 on 2024-08-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthProfessionalsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Mental Health Professionals Images')),
                ('FullName', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.CharField(blank=True, max_length=100, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Availability', models.CharField(blank=True, max_length=100, null=True)),
                ('Rating', models.CharField(blank=True, max_length=100, null=True)),
                ('AffiliatedClinic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
