# Generated by Django 5.1 on 2024-09-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_mentalhealthprofessionalsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('virtual_link', models.URLField(blank=True)),
                ('organizer', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('cover_image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
