# Generated by Django 5.1 on 2024-09-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentalHealthProfessionalsDB',
        ),
    ]
