# Generated by Django 5.1 on 2024-09-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_delete_mentalhealthprofessionalsdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
