# Generated by Django 5.1 on 2024-10-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_meditationsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AromatherapySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_name', models.CharField(choices=[('Lavender', 'Lavender'), ('Eucalyptus', 'Eucalyptus'), ('Peppermint', 'Peppermint'), ('Chamomile', 'Chamomile'), ('Tea Tree', 'Tea Tree'), ('Rosemary', 'Rosemary'), ('Lemon', 'Lemon'), ('Cinnamon', 'Cinnamon'), ('Lemongrass', 'Lemongrass'), ('Clary sage', 'Clary sage'), ('Geranium', 'Geranium'), ('Roman chamomile', 'Roman chamomile'), ('Ylang-Ylang', 'Ylang-Ylang')], max_length=100)),
                ('benefits', models.TextField()),
                ('usage_instructions', models.TextField()),
                ('recommended_time', models.CharField(max_length=100)),
                ('stress_level', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aromatherapy_images/')),
            ],
        ),
    ]
