# Generated by Django 5.1 on 2024-10-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_aromatherapysuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aromatherapysuggestion',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
