# Generated by Django 5.1 on 2024-10-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0011_exerciseroutine_recommended_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseroutine',
            name='equipment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
