# Generated by Django 5.1 on 2024-10-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0013_gratitudeprompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('multi-week', 'Multi-Week'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_tasks', models.IntegerField()),
            ],
        ),
    ]
