# Generated by Django 5.1 on 2024-10-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0016_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationsession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medi_images/'),
        ),
    ]
