# Generated by Django 5.1 on 2024-10-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0018_gratitudeprompt_week_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gratitudeprompt',
            name='week_number',
        ),
    ]
