# Generated by Django 5.1 on 2024-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0019_remove_gratitudeprompt_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitudeprompt',
            name='week_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
