# Generated by Django 5.1 on 2024-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregisterdb',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorregisterdb',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctorregisterdb',
            name='experience',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctorregisterdb',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
