# Generated by Django 5.1 on 2024-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0002_doctorregisterdb_dob_doctorregisterdb_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorregisterdb',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
