# Generated by Django 5.1 on 2024-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0004_remove_doctorregisterdb_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregisterdb',
            name='submitted_on',
        ),
        migrations.AlterField(
            model_name='doctorregisterdb',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
