# Generated by Django 5.1 on 2024-09-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0005_remove_doctorregisterdb_submitted_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorregisterdb',
            name='dob',
        ),
    ]
