# Generated by Django 5.1 on 2024-09-26 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0006_remove_doctorregisterdb_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregisterdb',
            name='submitted_on',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
