# Generated by Django 5.1 on 2024-09-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorApp', '0009_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
